# Generated by Django 4.0.2 on 2022-02-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='about',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
